version: "3.8"

services:
  authwebapp:
    build: .
    volumes:
      - .:/app
    ports:
      - "8008:8080"
    environment:
      - ConnectionString=Data Source=mssql;Initial Catalog=myapp;User Id=sa;Password=sql.12354?;Pooling=False;Max Pool Size=200;MultipleActiveResultSets=True

    depends_on:
      - mssql
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "sql.12354?"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer

volumes:
  sql_data:
